name: Feature Request
description: Suggest a new Feature.
title: "Feature: "
labels: [ "Type: Enhancement", "Priority: Medium", "Status: Pending" ]
body:
  - type: dropdown
    id: plugin
    attributes:
      label: For which plugin is the feature?
      multiple: false
      options:
        - FancyNpcs
        - FancyHolograms
        - FancyDialogs
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe your idea
      description: Please provide a raw or complete concent of the feature
      placeholder: A detailed description, possibly with examples or concept arts.
    validations:
      required: true
